name: Auto Deploy FastAPI with Docker Compose and Caddy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH and deploy to EC2
    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to the project directory
          cd ~/codes/fastapi-docker

          # Pull the latest changes from GitHub
          git pull origin master

          # Rebuild and start the containers with cleaning up orphan containers
          sudo docker-compose -f docker-compose.prod.yml up -d --build --remove-orphans