name: Auto Deploy FastAPI with Docker Compose to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH and deploy to EC2
    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to the project directory
          cd /path/to/your/project
          
          # Pull the latest changes from GitHub (if not using image build)
          git pull
          
          # Stop existing containers and clean up
          docker-compose down

          # Pull new image (if using external registry)
          docker-compose pull
          
          # Rebuild and start the containers
          docker-compose up -d --build
